const Data = [
    {
      id: "1",
      title: "Poha",
      category: "Breakfast",
      price: '$50',
      img: "https://c.ndtvimg.com/2021-08/loudr2go_aloo-poha_625x300_05_August_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
      desc: " Poha. Light, filling and easy to make, poha is one famous breakfast that is eaten almost everywhere in the country. And the best part is- it can be made in a number of ways.",
    },
    {
      id: "2",
      title: "Upma",
      category: "Breakfast",
      price: "$100",
      img: "https://c.ndtvimg.com/2021-04/37hi8sl_rava-upma_625x300_17_April_21.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
      desc: " A quintessential South Indian Breakfast! Made with protein-packed urad dal and semolina followed by crunchy veggies and curd, this recipe makes for a hearty .",
    },
    {
      id: "3",
      title: "Cheela",
      category: "Breakfast",
      price: '$150',
      img: "https://c.ndtvimg.com/2019-05/1afu8vt8_weight-loss-friendly-breakfast-paneer-besan-chilla_625x300_25_May_19.jpg?im=FaceCrop,algorithm=dnn,width=620,height=350",
      desc: "A staple across Indian households, moong dal is widely used in a number of Indian delicacies. One such delicacy is moong dal cheela. You can also add paneer to this recipe ",
    },
    {
      id: "4",
      title: "Channa Kulcha",
      category: "Lunch",
      price: '$50',
      img: "https://i.ndtvimg.com/i/2015-04/chana-kulcha_625x350_41429707001.jpg",
      desc: "A classic dish that never goes out of style. The quintessential chana kulcha  needs only a few ingredients - cumin powder, ginger, coriander powder, carom powder.",
    },
    {
      id: "5",
      title: "Egg Curry",
      category: "Lunch",
      price: "$100",
      img: "https://i.ndtvimg.com/i/2017-11/goan-egg-curry_620x350_41511515276.jpg",
      desc: "Eggs are a versatile food that can be cooked for any meal of the day. From breakfast to dinner, it can be a go-to food. Here is a mildly-spiced egg curry made with garlic.",
    },
    {
      id: "6",
      title: "Paneer Aachari",
      category: "Lunch",
      price: '$150',
      img: "https://i.ndtvimg.com/i/2015-04/paneer_625x350_61429707960.jpg",
      desc: "Don't get intimidated by the list of ingredients because not only are already in your kitchen cabinet, but also because all they'll need is 20 minutes of your time.",
    },
    {
      id: "7",
      title: "Fish Fry",
      category: "Dinner",
      price: "$100",
      img: "https://i.ndtvimg.com/i/2015-06/indian-dinner_625x350_41434360207.jpg",
      desc: "Get your daily dose of perfect protein. Pieces of surmai fish marinated in garlic, cumin, fennel, curry leaves, and tomatoes are pan-fried in refined oil and served hot.",
    },
    {
      id: "8",
      title: "Dum Alloo",
      category: "Dinner",
      price: '$50',
      img: "https://i.ndtvimg.com/i/2015-06/indian-dinner_625x350_51434362664.jpg",
      desc: "Your family will thank you for this fantastic bowl of dum aloo cooked Lakhnawi style. Take some potatoes, crumbled paneer, kasuri methi, butter, onions, and some ghee.",
    },
    {
      id: "9",
      title: "Malai Kofta",
      category: "Dinner",
      price: '$150',
      img: "https://i.ndtvimg.com/i/2017-10/makhmali-kofte_620x350_51508918483.jpg",
      desc: "A rich gravy made of khus khus, coconut and milk that tastes best with koftas made from khoya. This velvety and creamy recipe will leave you licking your fingers.",
    },
   
  ];
   
  export default Data;